image: docker:stable

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:dind

stages:
  - build
  - push
  - test

before_script:
  - docker info

build:
  stage: build
  script:
    # https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
    - docker build -f Dockerfile-C7-molecule -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:7-molecule .
    - docker images

push_to_dockerhub:
 stage: push
 only:
   - master
 script:
   - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
   - docker build -f Dockerfile-C7 -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:7 -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest .
   - docker build -f Dockerfile-C7-molecule -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:7-molecule .
   - docker build -f Dockerfile-C8 -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:8 .
   - docker build -f Dockerfile-C8-molecule -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:8-molecule .
   - docker images
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:7
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:7-molecule
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:8
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:8-molecule

test_docker_images:
  stage: test
  only:
   - master
  script:
    # dockerhub
    - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest cat /etc/os-release
    - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:7 cat /etc/os-release
    - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:7-molecule lsb_release -a
