FROM centos:7
# https://hub.docker.com/_/centos
ENV container=docker
RUN yum update -y && \
    yum clean all && \
(cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;
RUN yum makecache fast && \
    yum install -y python sudo yum-plugin-ovl bash redhat-lsb-core && \
    sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf &&  \
    yum clean all;
VOLUME [ "/sys/fs/cgroup" ]
CMD ["/usr/lib/systemd/systemd"]