FROM qwe1/docker-centos:7-systemd-enabled
RUN yum makecache fast && \
    yum install -y python sudo yum-plugin-ovl bash redhat-lsb-core && \
    sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf &&  \
    yum clean all;